### ISSUE TITLE
Koloboke

### ISSUE THREAD

**Issue by Neiko2002** [Speiger/Primitive-Collections-Benchmarks#1]
It might be interesting to compare the results with Koloboke, a library known for its fast HashMap and HashSet implementation for primitive data types.
https://github.com/leventov/Koloboke

**Comment by Speiger** [comment]
Right now I don't have time to work on this because other projects have priority right now.
But I will look into it the moment I have a free moment to breath again.

If you want to take things into your own hands to speed things up I am accepting/Prioritizing PRs.

**Comment by Speiger** [comment]
@Neiko2002 sorry that it took so long. A lot of bigger projects took way longer then expected. (Like 6 months longer)
Now Koloboke was added to the benchmarks.
Also cleanups and with a newer JVM+Faster CPU tests were made :)
